// 官方圣多纳释放法情绪表（AGFLAP-CAP）
// 来源：The Sedona Method® Course Workbook, ©1996-2010 Sedona Training Associates
// 英文为官方原版关键词；中文为标准参考译文，实际展示时 AI 会结合用户上下文动态翻译

export interface EmotionKeyword {
  en: string;
  zh: string; // 标准参考译文
}

export interface EmotionLevelInfo {
  name: string;       // 中文层级名
  nameEn: string;     // 官方英文层级名
  index: number;
  core: string;       // 中文核心描述
  coreEn: string;     // 英文核心描述
  keywords: EmotionKeyword[];
  isRestrictive: boolean;
}

export const EMOTION_LEVELS: EmotionLevelInfo[] = [
  {
    name: "冷漠",
    nameEn: "Apathy",
    index: 1,
    core: "无力、放弃",
    coreEn: "powerlessness, giving up",
    isRestrictive: true,
    keywords: [
      { en: "Bored", zh: "无聊" },
      { en: "Can't win", zh: "无法取胜" },
      { en: "Careless", zh: "漠不关心" },
      { en: "Cold", zh: "冷漠" },
      { en: "Cut-off", zh: "隔绝" },
      { en: "Dead", zh: "死气沉沉" },
      { en: "Defeated", zh: "败落感" },
      { en: "Depressed", zh: "压抑" },
      { en: "Demoralized", zh: "丧失斗志" },
      { en: "Desolate", zh: "荒凉孤寂" },
      { en: "Despair", zh: "绝望" },
      { en: "Discouraged", zh: "灰心" },
      { en: "Disillusioned", zh: "幻灭" },
      { en: "Doomed", zh: "注定失败" },
      { en: "Drained", zh: "精疲力竭" },
      { en: "Failure", zh: "失败" },
      { en: "Forgetful", zh: "恍惚健忘" },
      { en: "Futile", zh: "徒劳" },
      { en: "Giving up", zh: "放弃" },
      { en: "Hardened", zh: "心如铁石" },
      { en: "Hopeless", zh: "没有希望" },
      { en: "Humorless", zh: "毫无生气" },
      { en: "I can't", zh: "我做不到" },
      { en: "I don't care", zh: "无所谓" },
      { en: "I don't count", zh: "我无关紧要" },
      { en: "Inattentive", zh: "心不在焉" },
      { en: "Indecisive", zh: "优柔寡断" },
      { en: "Indifferent", zh: "冷淡" },
      { en: "Invisible", zh: "无存在感" },
      { en: "It's too late", zh: "太晚了" },
      { en: "Lazy", zh: "懒散" },
      { en: "Let it wait", zh: "随它去吧" },
      { en: "Listless", zh: "无精打采" },
      { en: "Loser", zh: "失败者" },
      { en: "Lost", zh: "迷失" },
      { en: "Negative", zh: "消极" },
      { en: "Numb", zh: "麻木" },
      { en: "Overwhelmed", zh: "不堪重负" },
      { en: "Powerless", zh: "无力" },
      { en: "Resigned", zh: "认命" },
      { en: "Shock", zh: "震惊" },
      { en: "Spaced out", zh: "发呆" },
      { en: "Stoned", zh: "麻痹迷离" },
      { en: "Stuck", zh: "卡住" },
      { en: "Too tired", zh: "太累了" },
      { en: "Unfeeling", zh: "感觉不到" },
      { en: "Unfocused", zh: "涣散" },
      { en: "Useless", zh: "没用" },
      { en: "Vague", zh: "模糊感" },
      { en: "Wasted", zh: "虚度" },
      { en: "What's the use?", zh: "有什么用呢" },
      { en: "Why try?", zh: "为什么还要尝试" },
      { en: "Worthless", zh: "毫无价值" },
    ],
  },
  {
    name: "悲伤",
    nameEn: "Grief",
    index: 2,
    core: "失去、受伤",
    coreEn: "loss, hurt",
    isRestrictive: true,
    keywords: [
      { en: "Abandoned", zh: "被遗弃" },
      { en: "Abused", zh: "被虐待" },
      { en: "Accused", zh: "被指责" },
      { en: "Anguished", zh: "极度痛苦" },
      { en: "Ashamed", zh: "羞耻" },
      { en: "Betrayed", zh: "被背叛" },
      { en: "Blue", zh: "忧郁" },
      { en: "Cheated", zh: "被欺骗" },
      { en: "Despair", zh: "绝望" },
      { en: "Disappointed", zh: "失望" },
      { en: "Distraught", zh: "悲痛欲绝" },
      { en: "Embarrassed", zh: "难堪" },
      { en: "Forgotten", zh: "被遗忘" },
      { en: "Guilty", zh: "内疚" },
      { en: "Heartbroken", zh: "心碎" },
      { en: "Heartache", zh: "心痛" },
      { en: "Heartsick", zh: "心里难受" },
      { en: "Helpless", zh: "无助" },
      { en: "Hurt", zh: "受伤" },
      { en: "If only", zh: "要是……就好了" },
      { en: "Ignored", zh: "被忽视" },
      { en: "Inadequate", zh: "不够好" },
      { en: "Inconsolable", zh: "无法平复" },
      { en: "It's not fair", zh: "这不公平" },
      { en: "Left out", zh: "被排在外" },
      { en: "Longing", zh: "思念" },
      { en: "Loss", zh: "失落" },
      { en: "Melancholy", zh: "忧郁" },
      { en: "Misunderstood", zh: "被误解" },
      { en: "Mourning", zh: "哀悼" },
      { en: "Neglected", zh: "被忽略" },
      { en: "Nobody cares", zh: "没人在乎" },
      { en: "Nobody loves me", zh: "没人爱我" },
      { en: "Nostalgia", zh: "怀旧" },
      { en: "Passed over", zh: "被跳过" },
      { en: "Pity", zh: "自怜" },
      { en: "Poor me", zh: "可怜的我" },
      { en: "Regret", zh: "后悔" },
      { en: "Rejected", zh: "被拒绝" },
      { en: "Remorse", zh: "悔恨" },
      { en: "Sadness", zh: "悲伤" },
      { en: "Sorrow", zh: "哀愁" },
      { en: "Tearful", zh: "含泪" },
      { en: "Tormented", zh: "煎熬" },
      { en: "Torn", zh: "撕裂感" },
      { en: "Tortured", zh: "折磨" },
      { en: "Unhappy", zh: "不快乐" },
      { en: "Unloved", zh: "感受不到爱" },
      { en: "Unwanted", zh: "不被需要" },
      { en: "Vulnerable", zh: "脆弱" },
      { en: "Why me?", zh: "为什么是我" },
      { en: "Wounded", zh: "受创" },
    ],
  },
  {
    name: "恐惧",
    nameEn: "Fear",
    index: 3,
    core: "不安全、威胁",
    coreEn: "insecurity, threat",
    isRestrictive: true,
    keywords: [
      { en: "Anxious", zh: "焦虑" },
      { en: "Apprehensive", zh: "忐忑" },
      { en: "Cautious", zh: "谨慎" },
      { en: "Clammy", zh: "手心出汗" },
      { en: "Cowardice", zh: "懦弱" },
      { en: "Defensive", zh: "防御" },
      { en: "Distrust", zh: "不信任" },
      { en: "Doubt", zh: "疑虑" },
      { en: "Dread", zh: "恐惧感" },
      { en: "Embarrassed", zh: "尴尬" },
      { en: "Evasive", zh: "回避" },
      { en: "Foreboding", zh: "不祥预感" },
      { en: "Frantic", zh: "惊慌失措" },
      { en: "Hesitant", zh: "犹豫" },
      { en: "Horrified", zh: "毛骨悚然" },
      { en: "Hysterical", zh: "歇斯底里" },
      { en: "Inhibited", zh: "受抑制" },
      { en: "Insecure", zh: "不安全感" },
      { en: "Irrational", zh: "不理性" },
      { en: "Nausea", zh: "恶心" },
      { en: "Nervous", zh: "紧张" },
      { en: "Panic", zh: "恐慌" },
      { en: "Paralyzed", zh: "瘫痪感" },
      { en: "Paranoid", zh: "偏执" },
      { en: "Scared", zh: "害怕" },
      { en: "Secretive", zh: "藏着掖着" },
      { en: "Shaky", zh: "发抖" },
      { en: "Shy", zh: "害羞" },
      { en: "Skeptical", zh: "怀疑" },
      { en: "Stage fright", zh: "怯场" },
      { en: "Superstitious", zh: "迷信" },
      { en: "Suspicious", zh: "多疑" },
      { en: "Tense", zh: "紧绷" },
      { en: "Terrified", zh: "极度恐惧" },
      { en: "Threatened", zh: "受到威胁" },
      { en: "Timid", zh: "胆怯" },
      { en: "Trapped", zh: "困住" },
      { en: "Uncertain", zh: "不确定" },
      { en: "Uneasy", zh: "不安" },
      { en: "Vulnerable", zh: "脆弱" },
      { en: "Want to escape", zh: "想逃跑" },
      { en: "Wary", zh: "警惕" },
      { en: "Worry", zh: "担忧" },
    ],
  },
  {
    name: "欲望",
    nameEn: "Lust",
    index: 4,
    core: "渴望、永不满足",
    coreEn: "craving, insatiable wanting",
    isRestrictive: true,
    keywords: [
      { en: "Abandon", zh: "放纵" },
      { en: "Anticipation", zh: "期待" },
      { en: "Callous", zh: "冷酷无情" },
      { en: "Can't wait", zh: "迫不及待" },
      { en: "Compulsive", zh: "强迫性冲动" },
      { en: "Craving", zh: "渴求" },
      { en: "Demanding", zh: "苛求" },
      { en: "Devious", zh: "狡猾" },
      { en: "Driven", zh: "被驱使" },
      { en: "Envy", zh: "嫉妒" },
      { en: "Exploitive", zh: "剥削性" },
      { en: "Fixated", zh: "执迷" },
      { en: "Frenzy", zh: "狂热" },
      { en: "Frustrated", zh: "挫败感" },
      { en: "Gluttonous", zh: "贪吃" },
      { en: "Greedy", zh: "贪婪" },
      { en: "Hoarding", zh: "囤积" },
      { en: "Hunger", zh: "饥渴" },
      { en: "I want", zh: "我想要" },
      { en: "Impatient", zh: "不耐烦" },
      { en: "Lascivious", zh: "好色" },
      { en: "Lecherous", zh: "淫荡" },
      { en: "Manipulative", zh: "操控" },
      { en: "Miserly", zh: "吝啬" },
      { en: "Must have it", zh: "必须得到" },
      { en: "Never enough", zh: "永远不够" },
      { en: "Never satisfied", zh: "永不满足" },
      { en: "Oblivious", zh: "浑然不觉" },
      { en: "Obsessed", zh: "执迷" },
      { en: "Overindulgent", zh: "过度放纵" },
      { en: "Possessive", zh: "占有欲" },
      { en: "Predatory", zh: "掠夺性" },
      { en: "Pushy", zh: "强迫他人" },
      { en: "Reckless", zh: "鲁莽" },
      { en: "Ruthless", zh: "冷酷无情" },
      { en: "Scheming", zh: "阴谋算计" },
      { en: "Selfish", zh: "自私" },
      { en: "Voracious", zh: "贪得无厌" },
      { en: "Wanton", zh: "放纵" },
      { en: "Wicked", zh: "邪恶" },
    ],
  },
  {
    name: "愤怒",
    nameEn: "Anger",
    index: 5,
    core: "攻击、反抗",
    coreEn: "attack, resistance",
    isRestrictive: true,
    keywords: [
      { en: "Abrasive", zh: "刺激性" },
      { en: "Aggressive", zh: "攻击性" },
      { en: "Annoyed", zh: "恼火" },
      { en: "Argumentative", zh: "争强好辩" },
      { en: "Belligerent", zh: "好斗" },
      { en: "Boiling", zh: "怒火沸腾" },
      { en: "Brooding", zh: "郁闷" },
      { en: "Caustic", zh: "刻薄" },
      { en: "Defiant", zh: "反抗" },
      { en: "Demanding", zh: "苛求" },
      { en: "Destructive", zh: "破坏性" },
      { en: "Disgust", zh: "厌恶" },
      { en: "Explosive", zh: "爆发性" },
      { en: "Fierce", zh: "凶猛" },
      { en: "Frustrated", zh: "挫败" },
      { en: "Fuming", zh: "冒火" },
      { en: "Furious", zh: "狂怒" },
      { en: "Harsh", zh: "严厉" },
      { en: "Hatred", zh: "仇恨" },
      { en: "Hostility", zh: "敌意" },
      { en: "Impatience", zh: "不耐烦" },
      { en: "Indignant", zh: "愤愤不平" },
      { en: "Irate", zh: "暴怒" },
      { en: "Jealous", zh: "嫉妒" },
      { en: "Livid", zh: "怒不可遏" },
      { en: "Mad", zh: "愤怒" },
      { en: "Mean", zh: "刻薄" },
      { en: "Merciless", zh: "残忍" },
      { en: "Murderous", zh: "杀气" },
      { en: "Outraged", zh: "义愤填膺" },
      { en: "Petulant", zh: "任性发火" },
      { en: "Pushy", zh: "强迫" },
      { en: "Rebellious", zh: "叛逆" },
      { en: "Resentment", zh: "怨恨" },
      { en: "Resistant", zh: "抵触" },
      { en: "Revolted", zh: "厌恶反感" },
      { en: "Rude", zh: "粗鲁" },
      { en: "Savage", zh: "野蛮" },
      { en: "Simmering", zh: "隐忍的怒火" },
      { en: "Sizzling", zh: "滚烫的愤怒" },
      { en: "Smoldering", zh: "闷燃的怒气" },
      { en: "Spiteful", zh: "恶意" },
      { en: "Steely", zh: "冷酷" },
      { en: "Stern", zh: "严厉" },
      { en: "Stewing", zh: "闷着的怒气" },
      { en: "Stubborn", zh: "固执" },
      { en: "Sullen", zh: "阴郁" },
      { en: "Vengeful", zh: "报复心" },
      { en: "Vicious", zh: "凶残" },
      { en: "Violent", zh: "暴力" },
      { en: "Volcanic", zh: "火山般爆发" },
      { en: "Wicked", zh: "邪恶" },
      { en: "Willful", zh: "任性" },
    ],
  },
  {
    name: "骄傲",
    nameEn: "Pride",
    index: 6,
    core: "优越、评判",
    coreEn: "superiority, judgment",
    isRestrictive: true,
    keywords: [
      { en: "Above reproach", zh: "自认无可指责" },
      { en: "Aloof", zh: "疏离" },
      { en: "Arrogant", zh: "傲慢" },
      { en: "Bigoted", zh: "固执偏见" },
      { en: "Boastful", zh: "自吹自擂" },
      { en: "Bored", zh: "无聊（优越感）" },
      { en: "Clever", zh: "自以为聪明" },
      { en: "Closed", zh: "封闭" },
      { en: "Complacent", zh: "自满" },
      { en: "Conceited", zh: "自负" },
      { en: "Contemptuous", zh: "轻蔑" },
      { en: "Cool", zh: "高冷" },
      { en: "Critical", zh: "批判" },
      { en: "Disdain", zh: "鄙视" },
      { en: "Dogmatic", zh: "教条" },
      { en: "False dignity", zh: "虚假尊严" },
      { en: "False humility", zh: "虚假谦逊" },
      { en: "False virtue", zh: "虚假美德" },
      { en: "Gloating", zh: "幸灾乐祸" },
      { en: "Haughty", zh: "傲慢" },
      { en: "Holier than thou", zh: "自以为是" },
      { en: "Hypocritical", zh: "虚伪" },
      { en: "Icy", zh: "冰冷" },
      { en: "Isolated", zh: "孤立" },
      { en: "Judgmental", zh: "评判" },
      { en: "Know-it-all", zh: "自以为无所不知" },
      { en: "Narrow-minded", zh: "心胸狭隘" },
      { en: "Never wrong", zh: "从不承认错误" },
      { en: "Opinionated", zh: "固执己见" },
      { en: "Overbearing", zh: "盛气凌人" },
      { en: "Patronizing", zh: "居高临下" },
      { en: "Pious", zh: "假虔诚" },
      { en: "Prejudiced", zh: "偏见" },
      { en: "Presumptuous", zh: "僭越" },
      { en: "Righteous", zh: "自以为正义" },
      { en: "Rigid", zh: "僵化" },
      { en: "Self-absorbed", zh: "只关注自己" },
      { en: "Self-satisfied", zh: "自我满足" },
      { en: "Selfish", zh: "自私" },
      { en: "Smug", zh: "沾沾自喜" },
      { en: "Snobbish", zh: "势利" },
      { en: "Special", zh: "自认特殊" },
      { en: "Spoiled", zh: "被宠坏" },
      { en: "Stoic", zh: "冷漠克制" },
      { en: "Stubborn", zh: "顽固" },
      { en: "Stuck-up", zh: "自命不凡" },
      { en: "Superior", zh: "高人一等" },
      { en: "Uncompromising", zh: "毫不妥协" },
      { en: "Unfeeling", zh: "无情" },
      { en: "Unforgiving", zh: "不宽恕" },
      { en: "Unyielding", zh: "不屈不挠" },
      { en: "Vain", zh: "虚荣" },
    ],
  },
  {
    name: "勇气",
    nameEn: "Courageousness",
    index: 7,
    core: "行动力、信心",
    coreEn: "action, confidence",
    isRestrictive: false,
    keywords: [
      { en: "Adventurous", zh: "勇于探索" },
      { en: "Alert", zh: "机警" },
      { en: "Alive", zh: "充满活力" },
      { en: "Assured", zh: "笃定" },
      { en: "Aware", zh: "觉知" },
      { en: "Centered", zh: "内心稳定" },
      { en: "Certain", zh: "确定" },
      { en: "Cheerful", zh: "愉快" },
      { en: "Clarity", zh: "清晰" },
      { en: "Compassion", zh: "慈悲" },
      { en: "Competent", zh: "有能力" },
      { en: "Confident", zh: "自信" },
      { en: "Creative", zh: "创造性" },
      { en: "Daring", zh: "大胆" },
      { en: "Decisive", zh: "果断" },
      { en: "Dynamic", zh: "充满活力" },
      { en: "Eager", zh: "热切" },
      { en: "Enthusiastic", zh: "热情" },
      { en: "Exhilaration", zh: "振奋" },
      { en: "Explorative", zh: "探索" },
      { en: "Flexible", zh: "灵活" },
      { en: "Focused", zh: "专注" },
      { en: "Giving", zh: "给予" },
      { en: "Happy", zh: "快乐" },
      { en: "Honorable", zh: "正直" },
      { en: "Humor", zh: "幽默" },
      { en: "I can", zh: "我可以" },
      { en: "Independent", zh: "独立" },
      { en: "Initiative", zh: "主动" },
      { en: "Integrity", zh: "正直诚信" },
      { en: "Invincible", zh: "无所畏惧" },
      { en: "Loving", zh: "充满爱" },
      { en: "Lucid", zh: "清醒" },
      { en: "Motivated", zh: "有动力" },
      { en: "Non-resistant", zh: "不抵抗" },
      { en: "Open", zh: "开放" },
      { en: "Optimistic", zh: "乐观" },
      { en: "Perspective", zh: "有视角" },
      { en: "Positive", zh: "积极" },
      { en: "Purposeful", zh: "有目标" },
      { en: "Receptive", zh: "接受" },
      { en: "Resilient", zh: "韧性" },
      { en: "Resourceful", zh: "足智多谋" },
      { en: "Responsive", zh: "回应" },
      { en: "Secure", zh: "安全感" },
      { en: "Self-sufficient", zh: "自足" },
      { en: "Sharp", zh: "敏锐" },
      { en: "Spontaneous", zh: "自发" },
      { en: "Strong", zh: "强大" },
      { en: "Supportive", zh: "支持" },
      { en: "Tireless", zh: "不知疲倦" },
      { en: "Vigorous", zh: "精力充沛" },
      { en: "Visionary", zh: "有远见" },
      { en: "Willing", zh: "愿意" },
      { en: "Zest", zh: "热情活力" },
    ],
  },
  {
    name: "接纳",
    nameEn: "Acceptance",
    index: 8,
    core: "满足、和谐",
    coreEn: "fulfillment, harmony",
    isRestrictive: false,
    keywords: [
      { en: "Abundance", zh: "丰盛" },
      { en: "Appreciative", zh: "感恩" },
      { en: "Balance", zh: "平衡" },
      { en: "Beautiful", zh: "感受到美" },
      { en: "Belonging", zh: "归属感" },
      { en: "Childlike", zh: "孩童般纯真" },
      { en: "Compassion", zh: "慈悲" },
      { en: "Considerate", zh: "体贴" },
      { en: "Delight", zh: "喜悦" },
      { en: "Elated", zh: "欢欣鼓舞" },
      { en: "Embracing", zh: "接纳" },
      { en: "Empathy", zh: "同理心" },
      { en: "Enriched", zh: "充实" },
      { en: "Everything's okay", zh: "一切都好" },
      { en: "Friendly", zh: "友好" },
      { en: "Fullness", zh: "圆满" },
      { en: "Gentle", zh: "温柔" },
      { en: "Glowing", zh: "发光" },
      { en: "Gracious", zh: "优雅" },
      { en: "Harmonious", zh: "和谐的" },
      { en: "Harmony", zh: "和谐" },
      { en: "I have", zh: "我拥有" },
      { en: "In tune", zh: "同频共振" },
      { en: "Intuitive", zh: "直觉" },
      { en: "Joyful", zh: "欢乐" },
      { en: "Loving", zh: "爱" },
      { en: "Magnanimous", zh: "宽宏大量" },
      { en: "Mellow", zh: "温润" },
      { en: "Naturalness", zh: "自然" },
      { en: "Nothing to change", zh: "无需改变" },
      { en: "Open", zh: "开放" },
      { en: "Playful", zh: "玩耍" },
      { en: "Radiant", zh: "光彩照人" },
      { en: "Receptive", zh: "接纳" },
      { en: "Secure", zh: "安全" },
      { en: "Soft", zh: "柔和" },
      { en: "Tender", zh: "温柔" },
      { en: "Understanding", zh: "理解" },
      { en: "Warm", zh: "温暖" },
      { en: "Well-being", zh: "幸福感" },
      { en: "Wonder", zh: "惊叹" },
    ],
  },
  {
    name: "平静",
    nameEn: "Peace",
    index: 9,
    core: "合一、圆满",
    coreEn: "oneness, wholeness",
    isRestrictive: false,
    keywords: [
      { en: "Ageless", zh: "超越年龄" },
      { en: "Awareness", zh: "觉知" },
      { en: "Being", zh: "存在" },
      { en: "Boundless", zh: "无边无际" },
      { en: "Calm", zh: "平静" },
      { en: "Centered", zh: "内心稳定" },
      { en: "Complete", zh: "完整" },
      { en: "Eternal", zh: "永恒" },
      { en: "Free", zh: "自由" },
      { en: "Fulfilled", zh: "圆满" },
      { en: "Glowing", zh: "发光" },
      { en: "I am", zh: "我在" },
      { en: "Imperturbable", zh: "泰然不动" },
      { en: "Knowingness", zh: "内在知晓" },
      { en: "Light", zh: "轻盈" },
      { en: "Oneness", zh: "合一" },
      { en: "Perfection", zh: "完美" },
      { en: "Presence", zh: "临在" },
      { en: "Pure", zh: "纯净" },
      { en: "Quiet", zh: "寂静" },
      { en: "Serenity", zh: "宁静" },
      { en: "Space", zh: "空间感" },
      { en: "Still", zh: "静止" },
      { en: "Timeless", zh: "超越时间" },
      { en: "Tranquility", zh: "安宁" },
      { en: "Unlimited", zh: "无限" },
      { en: "Whole", zh: "完整" },
    ],
  },
];

// 给 AI prompt 用的文本格式（英文为主，中文辅助）
export function buildEmotionTableText(): string {
  return EMOTION_LEVELS.map((level) => {
    const kwList = level.keywords.map((k) => `${k.en}（${k.zh}）`).join(", ");
    return `${level.index}. ${level.nameEn} / ${level.name}（${level.coreEn}）\nKeywords: ${kwList}`;
  }).join("\n\n");
}

// 根据英文单词查找所在层级
export function findLevelByKeyword(enWord: string): EmotionLevelInfo | undefined {
  const lower = enWord.toLowerCase();
  return EMOTION_LEVELS.find((level) =>
    level.keywords.some((k) => k.en.toLowerCase() === lower)
  );
}

// 根据英文单词查找标准中文译文
export function getDefaultZh(enWord: string): string {
  for (const level of EMOTION_LEVELS) {
    const kw = level.keywords.find((k) => k.en.toLowerCase() === enWord.toLowerCase());
    if (kw) return kw.zh;
  }
  return enWord;
}
